# Use the official Ruby image
FROM ruby:2.7.7

# lsb-release is crucial because it provides the necessary information to dynamically fetch the correct PostgreSQL repository based on the distribution
RUN apt-get update -qq && apt-get install -y lsb-release

# Add PostgreSQL repository dynamically based on the distribution
RUN echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list

# Add PostgreSQL signing key to verify downloads
RUN wget --no-check-certificate --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

# Update package list and install necessary packages - mimic prod server setup
RUN apt-get update -qq && apt-get install -y nodejs telnet vim zip cron graphviz wget

# prod server has postgres 14 (for some reason, didn't work without specifying the version)
RUN apt-get update -qq && apt-get install -y postgresql-client-14

# Create and set the working directory
RUN mkdir /app
WORKDIR /app

# Copy Gemfile and Gemfile.lock to install dependencies
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

# Install the specified version of Bundler and project dependencies
RUN gem install bundler -v 1.17.3
RUN bundle install

# Copy the entire application code
COPY . /app

# Default command to run the Rails server in development mode
CMD ["sleep", "infinity"]