class RemoveTimestamps < ActiveRecord::Migration
  def change
    remove_column :outcomes, :created_at, :datetime
    remove_column :outcomes, :updated_at, :datetime
    remove_column :baseline_measures, :created_at, :datetime
    remove_column :baseline_measures, :updated_at, :datetime
    remove_column :browse_conditions, :created_at, :datetime
    remove_column :browse_conditions, :updated_at, :datetime
    remove_column :browse_interventions, :created_at, :datetime
    remove_column :browse_interventions, :updated_at, :datetime
    remove_column :conditions, :created_at, :datetime
    remove_column :conditions, :updated_at, :datetime
    remove_column :derived_values, :created_at, :datetime
    remove_column :derived_values, :updated_at, :datetime
    remove_column :design_groups, :created_at, :datetime
    remove_column :design_groups, :updated_at, :datetime
    remove_column :drop_withdrawals, :created_at, :datetime
    remove_column :drop_withdrawals, :updated_at, :datetime
    remove_column :facilities, :created_at, :datetime
    remove_column :facilities, :updated_at, :datetime
    remove_column :groups, :created_at, :datetime
    remove_column :groups, :updated_at, :datetime
    remove_column :intervention_arm_group_labels, :created_at, :datetime
    remove_column :intervention_arm_group_labels, :updated_at, :datetime
    remove_column :intervention_other_names, :created_at, :datetime
    remove_column :intervention_other_names, :updated_at, :datetime
    remove_column :interventions, :created_at, :datetime
    remove_column :interventions, :updated_at, :datetime
    remove_column :keywords, :created_at, :datetime
    remove_column :keywords, :updated_at, :datetime
    remove_column :milestones, :created_at, :datetime
    remove_column :milestones, :updated_at, :datetime
    remove_column :outcome_analyses, :created_at, :datetime
    remove_column :outcome_analyses, :updated_at, :datetime
    remove_column :outcome_measures, :created_at, :datetime
    remove_column :outcome_measures, :updated_at, :datetime
    remove_column :participant_flows, :created_at, :datetime
    remove_column :participant_flows, :updated_at, :datetime
    remove_column :pma_mappings, :created_at, :datetime
    remove_column :pma_mappings, :updated_at, :datetime
    remove_column :pma_records, :created_at, :datetime
    remove_column :pma_records, :updated_at, :datetime
    remove_column :reported_events, :created_at, :datetime
    remove_column :reported_events, :updated_at, :datetime
    remove_column :reported_event_overviews, :created_at, :datetime
    remove_column :reported_event_overviews, :updated_at, :datetime
    remove_column :result_agreements, :created_at, :datetime
    remove_column :result_agreements, :updated_at, :datetime
    remove_column :result_contacts, :created_at, :datetime
    remove_column :result_contacts, :updated_at, :datetime
    remove_column :reviews, :created_at, :datetime
    remove_column :reviews, :updated_at, :datetime
    remove_column :search_results, :created_at, :datetime
    remove_column :search_results, :updated_at, :datetime
    remove_column :statistics, :created_at, :datetime
    remove_column :statistics, :updated_at, :datetime
  end
end
