class TestJson < ActiveRecord::Base

  def self.url
    'https://clinicaltrials.gov/api/info/study_structure?fmt=json'
  end
  def self.test_data
    {
      "Rank" => 1,
      "Study"=>{"type"=>"Object",
        "ProtocolSection"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/definitions.html",
          "IdentificationModule"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/definitions.html#identification",
            "NCTId"=>{"type"=>"String"},
            "NCTIdAliasList"=>{"type"=>"Array",
              "NCTIdAlias"=>{"type"=>"String"}
            },
            "OrgStudyIdInfo"=>{"type"=>"Object",
              "OrgStudyId"=>{"type"=>"String"},
              "OrgStudyIdType"=>{"type"=>"String"},
              "OrgStudyIdDomain"=>{"type"=>"String"},
              "OrgStudyIdLink"=>{"type"=>"String"}
            },
            "SecondaryIdInfoList"=>{"type"=>"Array",
              "SecondaryIdInfo"=>{"type"=>"Object",
                "SecondaryId"=>{"type"=>"String"},
                "SecondaryIdType"=>{"type"=>"String"},
                "SecondaryIdDomain"=>{"type"=>"String"},
                "SecondaryIdLink"=>{"type"=>"String"}
              }
            },
            "Organization"=>{"type"=>"Object",
              "OrgFullName"=>{"type"=>"String"},
              "OrgClass"=>{"type"=>"String"}
            },
            "BriefTitle"=>{"type"=>"String"},
            "OfficialTitle"=>{"type"=>"String"},
            "Acronym"=>{"type"=>"String"}
          },
          "StatusModule"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/definitions.html#status",
            "StatusVerifiedDate"=>{"type"=>"String"},
            "OverallStatus"=>{"type"=>"String"},
            "LastKnownStatus"=>{"type"=>"String"},
            "DelayedPosting"=>{"type"=>"String"},
            "WhyStopped"=>{"type"=>"String"},
            "ExpandedAccessInfo"=>{"type"=>"Object",
              "HasExpandedAccess"=>{"type"=>"String"},
              "ExpandedAccessNCTId"=>{"type"=>"String"},
              "ExpandedAccessStatusForNCTId"=>{"type"=>"String"}
            },
            "StartDateStruct"=>{"type"=>"Object",
              "StartDate"=>{"type"=>"String"},
              "StartDateType"=>{"type"=>"String"}
            },
            "PrimaryCompletionDateStruct"=>{"type"=>"Object",
              "PrimaryCompletionDate"=>{"type"=>"String"},
              "PrimaryCompletionDateType"=>{"type"=>"String"}
            },
            "CompletionDateStruct"=>{"type"=>"Object",
              "CompletionDate"=>{"type"=>"String"},
              "CompletionDateType"=>{"type"=>"String"}
            },
            "StudyFirstSubmitDate"=>{"type"=>"String"},
            "StudyFirstSubmitQCDate"=>{"type"=>"String"},
            "StudyFirstPostDateStruct"=>{"type"=>"Object",
              "StudyFirstPostDate"=>{"type"=>"String"},
              "StudyFirstPostDateType"=>{"type"=>"String"}
            },
            "ResultsFirstSubmitDate"=>{"type"=>"String"},
            "ResultsFirstSubmitQCDate"=>{"type"=>"String"},
            "ResultsFirstPostDateStruct"=>{"type"=>"Object",
              "ResultsFirstPostDate"=>{"type"=>"String"},
              "ResultsFirstPostDateType"=>{"type"=>"String"}
            },
            "DispFirstSubmitDate"=>{"type"=>"String"},
            "DispFirstSubmitQCDate"=>{"type"=>"String"},
            "DispFirstPostDateStruct"=>{"type"=>"Object",
              "DispFirstPostDate"=>{"type"=>"String"},
              "DispFirstPostDateType"=>{"type"=>"String"}
            },
            "LastUpdateSubmitDate"=>{"type"=>"String"},
            "LastUpdatePostDateStruct"=>{"type"=>"Object",
              "LastUpdatePostDate"=>{"type"=>"String"},
              "LastUpdatePostDateType"=>{"type"=>"String"}
            }
          },
          "SponsorCollaboratorsModule"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/definitions.html#sponsors",
            "ResponsibleParty"=>{"type"=>"Object",
              "ResponsiblePartyType"=>{"type"=>"String"},
              "ResponsiblePartyInvestigatorFullName"=>{"type"=>"String"},
              "ResponsiblePartyInvestigatorTitle"=>{"type"=>"String"},
              "ResponsiblePartyInvestigatorAffiliation"=>{"type"=>"String"},
              "ResponsiblePartyOldNameTitle"=>{"type"=>"String"},
              "ResponsiblePartyOldOrganization"=>{"type"=>"String"}
            },
            "LeadSponsor"=>{"type"=>"Object",
              "LeadSponsorName"=>{"type"=>"String"},
              "LeadSponsorClass"=>{"type"=>"String"}
            },
            "CollaboratorList"=>{"type"=>"Array",
              "Collaborator"=>{"type"=>"Object",
                "CollaboratorName"=>{"type"=>"String"},
                "CollaboratorClass"=>{"type"=>"String"}
              }
            }
          },
          "OversightModule"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/definitions.html#oversight",
            "OversightHasDMC"=>{"type"=>"String"},
            "IsFDARegulatedDrug"=>{"type"=>"String"},
            "IsFDARegulatedDevice"=>{"type"=>"String"},
            "IsUnapprovedDevice"=>{"type"=>"String"},
            "IsPPSD"=>{"type"=>"String"},
            "IsUSExport"=>{"type"=>"String"}
          },
          "DescriptionModule"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/definitions.html#description",
            "BriefSummary"=>{"type"=>"String"},
            "DetailedDescription"=>{"type"=>"String"}
          },
          "ConditionsModule"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/definitions.html#Conditions",
            "ConditionList"=>{"type"=>"Array",
              "Condition"=>{"type"=>"String"}
            },
            "KeywordList"=>{"type"=>"Array",
              "Keyword"=>{"type"=>"String"}
            }
          },
          "DesignModule"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/definitions.html#StudyDesign",
            "StudyType"=>{"type"=>"String","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/definitions.html#StudyType"},
            "ExpandedAccessTypes"=>{"type"=>"Object",
              "ExpAccTypeIndividual"=>{"type"=>"String"},
              "ExpAccTypeIntermediate"=>{"type"=>"String"},
              "ExpAccTypeTreatment"=>{"type"=>"String"}
            },
            "PatientRegistry"=>{"type"=>"String"},
            "TargetDuration"=>{"type"=>"String"},
            "PhaseList"=>{"type"=>"Array",
              "Phase"=>{"type"=>"String"}
            },
            "DesignInfo"=>{"type"=>"Object",
              "DesignAllocation"=>{"type"=>"String"},
              "DesignInterventionModel"=>{"type"=>"String"},
              "DesignInterventionModelDescription"=>{"type"=>"String"},
              "DesignPrimaryPurpose"=>{"type"=>"String"},
              "DesignObservationalModelList"=>{"type"=>"Array",
                "DesignObservationalModel"=>{"type"=>"String"}
              },
              "DesignTimePerspectiveList"=>{"type"=>"Array",
                "DesignTimePerspective"=>{"type"=>"String"}
              },
              "DesignMaskingInfo"=>{"type"=>"Object",
                "DesignMasking"=>{"type"=>"String"},
                "DesignMaskingDescription"=>{"type"=>"String"},
                "DesignWhoMaskedList"=>{"type"=>"Array",
                  "DesignWhoMasked"=>{"type"=>"String"}
                }
              }
            },
            "BioSpec"=>{"type"=>"Object",
              "BioSpecRetention"=>{"type"=>"String"},
              "BioSpecDescription"=>{"type"=>"String"}
            },
            "EnrollmentInfo"=>{"type"=>"Object",
              "EnrollmentCount"=>{"type"=>"String"},
              "EnrollmentType"=>{"type"=>"String"}
            }
          },
          "ArmsInterventionsModule"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/definitions.html#ArmsGroupsInterventions",
            "ArmGroupList"=>{"type"=>"Array",
              "ArmGroup"=>{"type"=>"Object",
                "ArmGroupLabel"=>{"type"=>"String"},
                "ArmGroupType"=>{"type"=>"String"},
                "ArmGroupDescription"=>{"type"=>"String"},
                "ArmGroupInterventionList"=>{"type"=>"Array",
                  "ArmGroupInterventionName"=>{"type"=>"String"}
                }
              }
            },
            "InterventionList"=>{"type"=>"Array",
              "Intervention"=>{"type"=>"Object",
                "InterventionType"=>{"type"=>"String"},
                "InterventionName"=>{"type"=>"String"},
                "InterventionDescription"=>{"type"=>"String"},
                "InterventionArmGroupLabelList"=>{"type"=>"Array",
                  "InterventionArmGroupLabel"=>{"type"=>"String"}
                },
                "InterventionOtherNameList"=>{"type"=>"Array",
                  "InterventionOtherName"=>{"type"=>"String"}
                }
              }
            }
          },
          "OutcomesModule"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/definitions.html#Outcomes",
            "PrimaryOutcomeList"=>{"type"=>"Array",
              "PrimaryOutcome"=>{"type"=>"Object",
                "PrimaryOutcomeMeasure"=>{"type"=>"String"},
                "PrimaryOutcomeDescription"=>{"type"=>"String"},
                "PrimaryOutcomeTimeFrame"=>{"type"=>"String"}
              }
            },
            "SecondaryOutcomeList"=>{"type"=>"Array",
              "SecondaryOutcome"=>{"type"=>"Object",
                "SecondaryOutcomeMeasure"=>{"type"=>"String"},
                "SecondaryOutcomeDescription"=>{"type"=>"String"},
                "SecondaryOutcomeTimeFrame"=>{"type"=>"String"}
              }
            },
            "OtherOutcomeList"=>{"type"=>"Array",
              "OtherOutcome"=>{"type"=>"Object",
                "OtherOutcomeMeasure"=>{"type"=>"String"},
                "OtherOutcomeDescription"=>{"type"=>"String"},
                "OtherOutcomeTimeFrame"=>{"type"=>"String"}
              }
            }
          },
          "EligibilityModule"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/definitions.html#Eligibility",
            "EligibilityCriteria"=>{"type"=>"String"},
            "HealthyVolunteers"=>{"type"=>"String"},
            "Gender"=>{"type"=>"String"},
            "GenderBased"=>{"type"=>"String"},
            "GenderDescription"=>{"type"=>"String"},
            "MinimumAge"=>{"type"=>"String"},
            "MaximumAge"=>{"type"=>"String"},
            "StdAgeList"=>{"type"=>"Array",
              "StdAge"=>{"type"=>"String"}
            },
            "StudyPopulation"=>{"type"=>"String"},
            "SamplingMethod"=>{"type"=>"String"}
          },
          "ContactsLocationsModule"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/definitions.html#Locations",
            "CentralContactList"=>{"type"=>"Array",
              "CentralContact"=>{"type"=>"Object",
                "CentralContactName"=>{"type"=>"String"},
                "CentralContactRole"=>{"type"=>"String"},
                "CentralContactPhone"=>{"type"=>"String"},
                "CentralContactPhoneExt"=>{"type"=>"String"},
                "CentralContactEMail"=>{"type"=>"String"}
              }
            },
            "OverallOfficialList"=>{"type"=>"Array",
              "OverallOfficial"=>{"type"=>"Object",
                "OverallOfficialName"=>{"type"=>"String"},
                "OverallOfficialAffiliation"=>{"type"=>"String"},
                "OverallOfficialRole"=>{"type"=>"String"}
              }
            },
            "LocationList"=>{"type"=>"Array",
              "Location"=>{"type"=>"Object",
                "LocationFacility"=>{"type"=>"String"},
                "LocationStatus"=>{"type"=>"String"},
                "LocationCity"=>{"type"=>"String"},
                "LocationState"=>{"type"=>"String"},
                "LocationZip"=>{"type"=>"String"},
                "LocationCountry"=>{"type"=>"String"},
                "LocationContactList"=>{"type"=>"Array",
                  "LocationContact"=>{"type"=>"Object",
                    "LocationContactName"=>{"type"=>"String"},
                    "LocationContactRole"=>{"type"=>"String"},
                    "LocationContactPhone"=>{"type"=>"String"},
                    "LocationContactPhoneExt"=>{"type"=>"String"},
                    "LocationContactEMail"=>{"type"=>"String"}
                  }
                }
              }
            }
          },
          "ReferencesModule"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/definitions.html#References",
            "ReferenceList"=>{"type"=>"Array",
              "Reference"=>{"type"=>"Object",
                "ReferencePMID"=>{"type"=>"String"},
                "ReferenceType"=>{"type"=>"String"},
                "ReferenceCitation"=>{"type"=>"String"},
                "RetractionList"=>{"type"=>"Array",
                  "Retraction"=>{"type"=>"Object",
                    "RetractionPMID"=>{"type"=>"String"},
                    "RetractionSource"=>{"type"=>"String"}
                  }
                }
              }
            },
            "SeeAlsoLinkList"=>{"type"=>"Array",
              "SeeAlsoLink"=>{"type"=>"Object",
                "SeeAlsoLinkLabel"=>{"type"=>"String"},
                "SeeAlsoLinkURL"=>{"type"=>"String"}
              }
            },
            "AvailIPDList"=>{"type"=>"Array",
              "AvailIPD"=>{"type"=>"Object",
                "AvailIPDId"=>{"type"=>"String"},
                "AvailIPDType"=>{"type"=>"String"},
                "AvailIPDURL"=>{"type"=>"String"},
                "AvailIPDComment"=>{"type"=>"String"}
              }
            }
          },
          "IPDSharingStatementModule"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/definitions.html#IPDSharing",
            "IPDSharing"=>{"type"=>"String"},
            "IPDSharingDescription"=>{"type"=>"String"},
            "IPDSharingInfoTypeList"=>{"type"=>"Array",
              "IPDSharingInfoType"=>{"type"=>"String"}
            },
            "IPDSharingTimeFrame"=>{"type"=>"String"},
            "IPDSharingAccessCriteria"=>{"type"=>"String"},
            "IPDSharingURL"=>{"type"=>"String"}
          }
        },
        "ResultsSection"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/results_definitions.html",
          "ParticipantFlowModule"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/results_definitions.html#Result_ParticipantFlow",
            "FlowPreAssignmentDetails"=>{"type"=>"String"},
            "FlowRecruitmentDetails"=>{"type"=>"String"},
            "FlowTypeUnitsAnalyzed"=>{"type"=>"String"},
            "FlowGroupList"=>{"type"=>"Array",
              "FlowGroup"=>{"type"=>"Object",
                "FlowGroupId"=>{"type"=>"String"},
                "FlowGroupTitle"=>{"type"=>"String"},
                "FlowGroupDescription"=>{"type"=>"String"}
              }
            },
            "FlowPeriodList"=>{"type"=>"Array",
              "FlowPeriod"=>{"type"=>"Object",
                "FlowPeriodTitle"=>{"type"=>"String"},
                "FlowMilestoneList"=>{"type"=>"Array",
                  "FlowMilestone"=>{"type"=>"Object",
                    "FlowMilestoneType"=>{"type"=>"String"},
                    "FlowMilestoneComment"=>{"type"=>"String"},
                    "FlowAchievementList"=>{"type"=>"Array",
                      "FlowAchievement"=>{"type"=>"Object",
                        "FlowAchievementGroupId"=>{"type"=>"String"},
                        "FlowAchievementComment"=>{"type"=>"String"},
                        "FlowAchievementNumSubjects"=>{"type"=>"String"},
                        "FlowAchievementNumUnits"=>{"type"=>"String"}
                      }
                    }
                  }
                },
                "FlowDropWithdrawList"=>{"type"=>"Array",
                  "FlowDropWithdraw"=>{"type"=>"Object",
                    "FlowDropWithdrawType"=>{"type"=>"String"},
                    "FlowDropWithdrawComment"=>{"type"=>"String"},
                    "FlowReasonList"=>{"type"=>"Array",
                      "FlowReason"=>{"type"=>"Object",
                        "FlowReasonGroupId"=>{"type"=>"String"},
                        "FlowReasonComment"=>{"type"=>"String"},
                        "FlowReasonNumSubjects"=>{"type"=>"String"},
                        "FlowReasonNumUnits"=>{"type"=>"String"}
                      }
                    }
                  }
                }
              }
            }
          },
          "BaselineCharacteristicsModule"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/results_definitions.html#Result_Baseline",
            "BaselinePopulationDescription"=>{"type"=>"String"},
            "BaselineTypeUnitsAnalyzed"=>{"type"=>"String"},
            "BaselineGroupList"=>{"type"=>"Array",
              "BaselineGroup"=>{"type"=>"Object",
                "BaselineGroupId"=>{"type"=>"String"},
                "BaselineGroupTitle"=>{"type"=>"String"},
                "BaselineGroupDescription"=>{"type"=>"String"}
              }
            },
            "BaselineDenomList"=>{"type"=>"Array",
              "BaselineDenom"=>{"type"=>"Object",
                "BaselineDenomUnits"=>{"type"=>"String"},
                "BaselineDenomCountList"=>{"type"=>"Array",
                  "BaselineDenomCount"=>{"type"=>"Object",
                    "BaselineDenomCountGroupId"=>{"type"=>"String"},
                    "BaselineDenomCountValue"=>{"type"=>"String"}
                  }
                }
              }
            },
            "BaselineMeasureList"=>{"type"=>"Array",
              "BaselineMeasure"=>{"type"=>"Object",
                "BaselineMeasureTitle"=>{"type"=>"String"},
                "BaselineMeasureDescription"=>{"type"=>"String"},
                "BaselineMeasurePopulationDescription"=>{"type"=>"String"},
                "BaselineMeasureParamType"=>{"type"=>"String"},
                "BaselineMeasureDispersionType"=>{"type"=>"String"},
                "BaselineMeasureUnitOfMeasure"=>{"type"=>"String"},
                "BaselineMeasureCalculatePct"=>{"type"=>"String"},
                "BaselineMeasureDenomUnitsSelected"=>{"type"=>"String"},
                "BaselineMeasureDenomList"=>{"type"=>"Array",
                  "BaselineMeasureDenom"=>{"type"=>"Object",
                    "BaselineMeasureDenomUnits"=>{"type"=>"String"},
                    "BaselineMeasureDenomCountList"=>{"type"=>"Array",
                      "BaselineMeasureDenomCount"=>{"type"=>"Object",
                        "BaselineMeasureDenomCountGroupId"=>{"type"=>"String"},
                        "BaselineMeasureDenomCountValue"=>{"type"=>"String"}
                      }
                    }
                  }
                },
                "BaselineClassList"=>{"type"=>"Array",
                  "BaselineClass"=>{"type"=>"Object",
                    "BaselineClassTitle"=>{"type"=>"String"},
                    "BaselineClassDenomList"=>{"type"=>"Array",
                      "BaselineClassDenom"=>{"type"=>"Object",
                        "BaselineClassDenomUnits"=>{"type"=>"String"},
                        "BaselineClassDenomCountList"=>{"type"=>"Array",
                          "BaselineClassDenomCount"=>{"type"=>"Object",
                            "BaselineClassDenomCountGroupId"=>{"type"=>"String"},
                            "BaselineClassDenomCountValue"=>{"type"=>"String"}
                          }
                        }
                      }
                    },
                    "BaselineCategoryList"=>{"type"=>"Array",
                      "BaselineCategory"=>{"type"=>"Object",
                        "BaselineCategoryTitle"=>{"type"=>"String"},
                        "BaselineMeasurementList"=>{"type"=>"Array",
                          "BaselineMeasurement"=>{"type"=>"Object",
                            "BaselineMeasurementGroupId"=>{"type"=>"String"},
                            "BaselineMeasurementValue"=>{"type"=>"String"},
                            "BaselineMeasurementSpread"=>{"type"=>"String"},
                            "BaselineMeasurementLowerLimit"=>{"type"=>"String"},
                            "BaselineMeasurementUpperLimit"=>{"type"=>"String"},
                            "BaselineMeasurementComment"=>{"type"=>"String"}
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "OutcomeMeasuresModule"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/results_definitions.html#Result_Outcome_Measure",
            "OutcomeMeasureList"=>{"type"=>"Array",
              "OutcomeMeasure"=>{"type"=>"Object",
                "OutcomeMeasureType"=>{"type"=>"String"},
                "OutcomeMeasureTitle"=>{"type"=>"String"},
                "OutcomeMeasureDescription"=>{"type"=>"String"},
                "OutcomeMeasurePopulationDescription"=>{"type"=>"String"},
                "OutcomeMeasureReportingStatus"=>{"type"=>"String"},
                "OutcomeMeasureAnticipatedPostingDate"=>{"type"=>"String"},
                "OutcomeMeasureParamType"=>{"type"=>"String"},
                "OutcomeMeasureDispersionType"=>{"type"=>"String"},
                "OutcomeMeasureUnitOfMeasure"=>{"type"=>"String"},
                "OutcomeMeasureCalculatePct"=>{"type"=>"String"},
                "OutcomeMeasureTimeFrame"=>{"type"=>"String"},
                "OutcomeMeasureTypeUnitsAnalyzed"=>{"type"=>"String"},
                "OutcomeMeasureDenomUnitsSelected"=>{"type"=>"String"},
                "OutcomeGroupList"=>{"type"=>"Array",
                  "OutcomeGroup"=>{"type"=>"Object",
                    "OutcomeGroupId"=>{"type"=>"String"},
                    "OutcomeGroupTitle"=>{"type"=>"String"},
                    "OutcomeGroupDescription"=>{"type"=>"String"}
                  }
                },
                "OutcomeDenomList"=>{"type"=>"Array",
                  "OutcomeDenom"=>{"type"=>"Object",
                    "OutcomeDenomUnits"=>{"type"=>"String"},
                    "OutcomeDenomCountList"=>{"type"=>"Array",
                      "OutcomeDenomCount"=>{"type"=>"Object",
                        "OutcomeDenomCountGroupId"=>{"type"=>"String"},
                        "OutcomeDenomCountValue"=>{"type"=>"String"}
                      }
                    }
                  }
                },
                "OutcomeClassList"=>{"type"=>"Array",
                  "OutcomeClass"=>{"type"=>"Object",
                    "OutcomeClassTitle"=>{"type"=>"String"},
                    "OutcomeClassDenomList"=>{"type"=>"Array",
                      "OutcomeClassDenom"=>{"type"=>"Object",
                        "OutcomeClassDenomUnits"=>{"type"=>"String"},
                        "OutcomeClassDenomCountList"=>{"type"=>"Array",
                          "OutcomeClassDenomCount"=>{"type"=>"Object",
                            "OutcomeClassDenomCountGroupId"=>{"type"=>"String"},
                            "OutcomeClassDenomCountValue"=>{"type"=>"String"}
                          }
                        }
                      }
                    },
                    "OutcomeCategoryList"=>{"type"=>"Array",
                      "OutcomeCategory"=>{"type"=>"Object",
                        "OutcomeCategoryTitle"=>{"type"=>"String"},
                        "OutcomeMeasurementList"=>{"type"=>"Array",
                          "OutcomeMeasurement"=>{"type"=>"Object",
                            "OutcomeMeasurementGroupId"=>{"type"=>"String"},
                            "OutcomeMeasurementValue"=>{"type"=>"String"},
                            "OutcomeMeasurementSpread"=>{"type"=>"String"},
                            "OutcomeMeasurementLowerLimit"=>{"type"=>"String"},
                            "OutcomeMeasurementUpperLimit"=>{"type"=>"String"},
                            "OutcomeMeasurementComment"=>{"type"=>"String"}
                          }
                        }
                      }
                    }
                  }
                },
                "OutcomeAnalysisList"=>{"type"=>"Array","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/results_definitions.html#Result_Outcome_Analysis",
                  "OutcomeAnalysis"=>{"type"=>"Object",
                    "OutcomeAnalysisGroupIdList"=>{"type"=>"Array",
                      "OutcomeAnalysisGroupId"=>{"type"=>"String"}
                    },
                    "OutcomeAnalysisGroupDescription"=>{"type"=>"String"},
                    "OutcomeAnalysisTestedNonInferiority"=>{"type"=>"String"},
                    "OutcomeAnalysisNonInferiorityType"=>{"type"=>"String"},
                    "OutcomeAnalysisNonInferiorityComment"=>{"type"=>"String"},
                    "OutcomeAnalysisPValue"=>{"type"=>"String"},
                    "OutcomeAnalysisPValueComment"=>{"type"=>"String"},
                    "OutcomeAnalysisStatisticalMethod"=>{"type"=>"String"},
                    "OutcomeAnalysisStatisticalComment"=>{"type"=>"String"},
                    "OutcomeAnalysisParamType"=>{"type"=>"String"},
                    "OutcomeAnalysisParamValue"=>{"type"=>"String"},
                    "OutcomeAnalysisCIPctValue"=>{"type"=>"String"},
                    "OutcomeAnalysisCINumSides"=>{"type"=>"String"},
                    "OutcomeAnalysisCILowerLimit"=>{"type"=>"String"},
                    "OutcomeAnalysisCIUpperLimit"=>{"type"=>"String"},
                    "OutcomeAnalysisCILowerLimitComment"=>{"type"=>"String"},
                    "OutcomeAnalysisCIUpperLimitComment"=>{"type"=>"String"},
                    "OutcomeAnalysisDispersionType"=>{"type"=>"String"},
                    "OutcomeAnalysisDispersionValue"=>{"type"=>"String"},
                    "OutcomeAnalysisEstimateComment"=>{"type"=>"String"},
                    "OutcomeAnalysisOtherAnalysisDescription"=>{"type"=>"String"}
                  }
                }
              }
            }
          },
          "AdverseEventsModule"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/results_definitions.html#Result_AdverseEvents",
            "EventsFrequencyThreshold"=>{"type"=>"String"},
            "EventsTimeFrame"=>{"type"=>"String"},
            "EventsDescription"=>{"type"=>"String"},
            "EventGroupList"=>{"type"=>"Array",
              "EventGroup"=>{"type"=>"Object",
                "EventGroupId"=>{"type"=>"String"},
                "EventGroupTitle"=>{"type"=>"String"},
                "EventGroupDescription"=>{"type"=>"String"},
                "EventGroupDeathsNumAffected"=>{"type"=>"String"},
                "EventGroupDeathsNumAtRisk"=>{"type"=>"String"},
                "EventGroupSeriousNumAffected"=>{"type"=>"String"},
                "EventGroupSeriousNumAtRisk"=>{"type"=>"String"},
                "EventGroupOtherNumAffected"=>{"type"=>"String"},
                "EventGroupOtherNumAtRisk"=>{"type"=>"String"}
              }
            },
            "SeriousEventList"=>{"type"=>"Array",
              "SeriousEvent"=>{"type"=>"Object",
                "SeriousEventTerm"=>{"type"=>"String"},
                "SeriousEventOrganSystem"=>{"type"=>"String"},
                "SeriousEventSourceVocabulary"=>{"type"=>"String"},
                "SeriousEventAssessmentType"=>{"type"=>"String"},
                "SeriousEventNotes"=>{"type"=>"String"},
                "SeriousEventStatsList"=>{"type"=>"Array",
                  "SeriousEventStats"=>{"type"=>"Object",
                    "SeriousEventStatsGroupId"=>{"type"=>"String"},
                    "SeriousEventStatsNumEvents"=>{"type"=>"String"},
                    "SeriousEventStatsNumAffected"=>{"type"=>"String"},
                    "SeriousEventStatsNumAtRisk"=>{"type"=>"String"}
                  }
                }
              }
            },
            "OtherEventList"=>{"type"=>"Array",
              "OtherEvent"=>{"type"=>"Object",
                "OtherEventTerm"=>{"type"=>"String"},
                "OtherEventOrganSystem"=>{"type"=>"String"},
                "OtherEventSourceVocabulary"=>{"type"=>"String"},
                "OtherEventAssessmentType"=>{"type"=>"String"},
                "OtherEventNotes"=>{"type"=>"String"},
                "OtherEventStatsList"=>{"type"=>"Array",
                  "OtherEventStats"=>{"type"=>"Object",
                    "OtherEventStatsGroupId"=>{"type"=>"String"},
                    "OtherEventStatsNumEvents"=>{"type"=>"String"},
                    "OtherEventStatsNumAffected"=>{"type"=>"String"},
                    "OtherEventStatsNumAtRisk"=>{"type"=>"String"}
                  }
                }
              }
            }
          },
          "MoreInfoModule"=>{"type"=>"Object",
            "LimitationsAndCaveats"=>{"type"=>"String","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/results_definitions.html#Result_LimitationsAndCaveats_description"},
            "CertainAgreement"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/results_definitions.html#Result_CertainAgreement",
              "AgreementPISponsorEmployee"=>{"type"=>"String"},
              "AgreementRestrictionType"=>{"type"=>"String"},
              "AgreementRestrictiveAgreement"=>{"type"=>"String"},
              "AgreementOtherDetails"=>{"type"=>"String"}
            },
            "PointOfContact"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/results_definitions.html#Result_PointOfContact",
              "PointOfContactTitle"=>{"type"=>"String"},
              "PointOfContactOrganization"=>{"type"=>"String"},
              "PointOfContactEMail"=>{"type"=>"String"},
              "PointOfContactPhone"=>{"type"=>"String"},
              "PointOfContactPhoneExt"=>{"type"=>"String"}
            }
          }
        },
        "AnnotationSection"=>{"type"=>"Object",
          "AnnotationModule"=>{"type"=>"Object",
            "UnpostedAnnotation"=>{"type"=>"Object",
              "UnpostedResponsibleParty"=>{"type"=>"String"},
              "UnpostedEventList"=>{"type"=>"Array",
                "UnpostedEvent"=>{"type"=>"Object",
                  "UnpostedEventType"=>{"type"=>"String"},
                  "UnpostedEventDate"=>{"type"=>"String"}
                }
              }
            }
          }
        },
        "DocumentSection"=>{"type"=>"Object",
          "LargeDocumentModule"=>{"type"=>"Object","dedLink"=>"https=>//prsinfo.clinicaltrials.gov/results_definitions.html#DocumentUploadLabel",
            "LargeDocList"=>{"type"=>"Array",
              "LargeDoc"=>{"type"=>"Object",
                "LargeDocTypeAbbrev"=>{"type"=>"String"},
                "LargeDocHasProtocol"=>{"type"=>"String"},
                "LargeDocHasSAP"=>{"type"=>"String"},
                "LargeDocHasICF"=>{"type"=>"String"},
                "LargeDocLabel"=>{"type"=>"String"},
                "LargeDocDate"=>{"type"=>"String"},
                "LargeDocUploadDate"=>{"type"=>"String"},
                "LargeDocFilename"=>{"type"=>"String"}
              }
            }
          }
        },
        "DerivedSection"=>{"type"=>"Object",
          "MiscInfoModule"=>{"type"=>"Object",
            "VersionHolder"=>{"type"=>"String"},
            "RemovedCountryList"=>{"type"=>"Array",
              "RemovedCountry"=>{"type"=>"String"}
            }
          },
          "ConditionBrowseModule"=>{"type"=>"Object",
            "ConditionMeshList"=>{"type"=>"Array",
              "ConditionMesh"=>{"type"=>"Object",
                "ConditionMeshId"=>{"type"=>"String"},
                "ConditionMeshTerm"=>{"type"=>"String"}
              }
            },
            "ConditionAncestorList"=>{"type"=>"Array",
              "ConditionAncestor"=>{"type"=>"Object",
                "ConditionAncestorId"=>{"type"=>"String"},
                "ConditionAncestorTerm"=>{"type"=>"String"}
              }
            },
            "ConditionBrowseLeafList"=>{"type"=>"Array",
              "ConditionBrowseLeaf"=>{"type"=>"Object",
                "ConditionBrowseLeafId"=>{"type"=>"String"},
                "ConditionBrowseLeafName"=>{"type"=>"String"},
                "ConditionBrowseLeafAsFound"=>{"type"=>"String"},
                "ConditionBrowseLeafRelevance"=>{"type"=>"String"}
              }
            },
            "ConditionBrowseBranchList"=>{"type"=>"Array",
              "ConditionBrowseBranch"=>{"type"=>"Object",
                "ConditionBrowseBranchAbbrev"=>{"type"=>"String"},
                "ConditionBrowseBranchName"=>{"type"=>"String"}
              }
            }
          },
          "InterventionBrowseModule"=>{"type"=>"Object",
            "InterventionMeshList"=>{"type"=>"Array",
              "InterventionMesh"=>{"type"=>"Object",
                "InterventionMeshId"=>{"type"=>"String"},
                "InterventionMeshTerm"=>{"type"=>"String"}
              }
            },
            "InterventionAncestorList"=>{"type"=>"Array",
              "InterventionAncestor"=>{"type"=>"Object",
                "InterventionAncestorId"=>{"type"=>"String"},
                "InterventionAncestorTerm"=>{"type"=>"String"}
              }
            },
            "InterventionBrowseLeafList"=>{"type"=>"Array",
              "InterventionBrowseLeaf"=>{"type"=>"Object",
                "InterventionBrowseLeafId"=>{"type"=>"String"},
                "InterventionBrowseLeafName"=>{"type"=>"String"},
                "InterventionBrowseLeafAsFound"=>{"type"=>"String"},
                "InterventionBrowseLeafRelevance"=>{"type"=>"String"}
              }
            },
            "InterventionBrowseBranchList"=>{"type"=>"Array",
              "InterventionBrowseBranch"=>{"type"=>"Object",
                "InterventionBrowseBranchAbbrev"=>{"type"=>"String"},
                "InterventionBrowseBranchName"=>{"type"=>"String"}
              }
            }
          }
        }
      }
    }
  end

  def self.baseline_class
    {"BaselineClass"=>[{"BaselineCategoryList"=>{"BaselineCategory"=>[{"BaselineCategoryTitle"=>"American Indian or Alaska Native", "BaselineMeasurementList"=>{"BaselineMeasurement"=>[{"BaselineMeasurementValue"=>"0", "BaselineMeasurementGroupId"=>"BG000"}, {"BaselineMeasurementValue"=>"0", "BaselineMeasurementGroupId"=>"BG001"}, {"BaselineMeasurementValue"=>"0", "BaselineMeasurementGroupId"=>"BG002"}]}}, {"BaselineCategoryTitle"=>"Asian", "BaselineMeasurementList"=>{"BaselineMeasurement"=>[{"BaselineMeasurementValue"=>"0", "BaselineMeasurementGroupId"=>"BG000"}, {"BaselineMeasurementValue"=>"0", "BaselineMeasurementGroupId"=>"BG001"}, {"BaselineMeasurementValue"=>"0", "BaselineMeasurementGroupId"=>"BG002"}]}}, {"BaselineCategoryTitle"=>"Native Hawaiian or Other Pacific Islander", "BaselineMeasurementList"=>{"BaselineMeasurement"=>[{"BaselineMeasurementValue"=>"0", "BaselineMeasurementGroupId"=>"BG000"}, {"BaselineMeasurementValue"=>"0", "BaselineMeasurementGroupId"=>"BG001"}, {"BaselineMeasurementValue"=>"0", "BaselineMeasurementGroupId"=>"BG002"}]}}, {"BaselineCategoryTitle"=>"Black or African American", "BaselineMeasurementList"=>{"BaselineMeasurement"=>[{"BaselineMeasurementValue"=>"1", "BaselineMeasurementGroupId"=>"BG000"}, {"BaselineMeasurementValue"=>"1", "BaselineMeasurementGroupId"=>"BG001"}, {"BaselineMeasurementValue"=>"2", "BaselineMeasurementGroupId"=>"BG002"}]}}, {"BaselineCategoryTitle"=>"White", "BaselineMeasurementList"=>{"BaselineMeasurement"=>[{"BaselineMeasurementValue"=>"15", "BaselineMeasurementGroupId"=>"BG000"}, {"BaselineMeasurementValue"=>"13", "BaselineMeasurementGroupId"=>"BG001"}, {"BaselineMeasurementValue"=>"28", "BaselineMeasurementGroupId"=>"BG002"}]}}, {"BaselineCategoryTitle"=>"More than one race", "BaselineMeasurementList"=>{"BaselineMeasurement"=>[{"BaselineMeasurementValue"=>"0", "BaselineMeasurementGroupId"=>"BG000"}, {"BaselineMeasurementValue"=>"0", "BaselineMeasurementGroupId"=>"BG001"}, {"BaselineMeasurementValue"=>"0", "BaselineMeasurementGroupId"=>"BG002"}]}}, {"BaselineCategoryTitle"=>"Unknown or Not Reported", "BaselineMeasurementList"=>{"BaselineMeasurement"=>[{"BaselineMeasurementValue"=>"0", "BaselineMeasurementGroupId"=>"BG000"}, {"BaselineMeasurementValue"=>"0", "BaselineMeasurementGroupId"=>"BG001"}, {"BaselineMeasurementValue"=>"0", "BaselineMeasurementGroupId"=>"BG002"}]}}]}}]}
  end

  def self.baseline_measurement_list
    "BaselineMeasureList":{
                "BaselineMeasure":[
                  {
                    "BaselineMeasureTitle":"Age, Categorical",
                    "BaselineMeasureDescription":"Age- was calculated based on patients identification (ID) number (in Poland each ID number contains date of birth).",
                    "BaselineMeasureParamType":"Count of Participants",
                    "BaselineMeasureUnitOfMeasure":"Participants",
                    "BaselineMeasureDenomUnitsSelected":"Participants",
                    "BaselineClassList":{
                      "BaselineClass":[
                        {
                          "BaselineCategoryList":{
                            "BaselineCategory":[
                              {
                                "BaselineCategoryTitle":"<=18 years",
                                "BaselineMeasurementList":{
                                  "BaselineMeasurement":[
                                    {
                                      "BaselineMeasurementGroupId":"BG000",
                                      "BaselineMeasurementValue":"0"
                                    }
                                  ]
                                }
                              },{
                                "BaselineCategoryTitle":"Between 18 and 65 years",
                                "BaselineMeasurementList":{
                                  "BaselineMeasurement":[
                                    {
                                      "BaselineMeasurementGroupId":"BG000",
                                      "BaselineMeasurementValue":"478"
                                    }
                                  ]
                                }
                              },{
                                "BaselineCategoryTitle":">=65 years",
                                "BaselineMeasurementList":{
                                  "BaselineMeasurement":[
                                    {
                                      "BaselineMeasurementGroupId":"BG000",
                                      "BaselineMeasurementValue":"496"
                                    }
                                  ]
                                }
                              }
                            ]
                          }
                        }
                      ]
                    }
                  },
                  {
                    "BaselineMeasureTitle":"Age, Continuous",
                    "BaselineMeasureParamType":"Mean",
                    "BaselineMeasureDispersionType":"Standard Deviation",
                    "BaselineMeasureUnitOfMeasure":"years",
                    "BaselineMeasureDenomUnitsSelected":"Participants",
                    "BaselineClassList":{
                      "BaselineClass":[
                        {
                          "BaselineCategoryList":{
                            "BaselineCategory":[
                              {
                                "BaselineMeasurementList":{
                                  "BaselineMeasurement":[
                                    {
                                      "BaselineMeasurementGroupId":"BG000",
                                      "BaselineMeasurementValue":"64.6",
                                      "BaselineMeasurementSpread":"11.15"
                                    }
                                  ]
                                }
                              }
                            ]
                          }
                        }
                      ]
                    }
                  },
                  {
                    "BaselineMeasureTitle":"Sex: Female, Male",
                    "BaselineMeasureParamType":"Count of Participants",
                    "BaselineMeasureUnitOfMeasure":"Participants",
                    "BaselineMeasureDenomUnitsSelected":"Participants",
                    "BaselineClassList":{
                      "BaselineClass":[
                        {
                          "BaselineCategoryList":{
                            "BaselineCategory":[
                              {
                                "BaselineCategoryTitle":"Female",
                                "BaselineMeasurementList":{
                                  "BaselineMeasurement":[
                                    {
                                      "BaselineMeasurementGroupId":"BG000",
                                      "BaselineMeasurementValue":"523"
                                    }
                                  ]
                                }
                              },{
                                "BaselineCategoryTitle":"Male",
                                "BaselineMeasurementList":{
                                  "BaselineMeasurement":[
                                    {
                                      "BaselineMeasurementGroupId":"BG000",
                                      "BaselineMeasurementValue":"451"
                                    }
                                  ]
                                }
                              }
                            ]
                          }
                        }
                      ]
                    }
                  },
                  {
                    "BaselineMeasureTitle":"Region of Enrollment",
                    "BaselineMeasureParamType":"Number",
                    "BaselineMeasureUnitOfMeasure":"participants",
                    "BaselineMeasureDenomUnitsSelected":"Participants",
                    "BaselineClassList":{
                      "BaselineClass":[
                        {
                          "BaselineClassTitle":"Poland",
                          "BaselineCategoryList":{
                            "BaselineCategory":[
                              {
                                "BaselineMeasurementList":{
                                  "BaselineMeasurement":[
                                    {
                                      "BaselineMeasurementGroupId":"BG000",
                                      "BaselineMeasurementValue":"974"
                                    }
                                  ]
                                }
                              }
                            ]
                          }
                        }
                      ]
                    }
                  }
                ]
              }
    end
end